### ISSUE TITLE
Preview script not defined

### ISSUE THREAD

**Issue by alialaa** [oPauloChaves/react-pwa-webpack-starter#6]
hello, yarn run preview is not working because it's notdefined in package.json

**Comment by oPauloChaves** [comment]
Thanks man!

I just updated the README to reflect the newest changes. I setup React + Babel 7 + PWA with Workbox and enabled Prettier.

**Comment by alialaa** [comment]
Thanks, I have another question, how can I remove CSS modules? I don't wan't my class names changed, I removed modules: true in css-loader but it didn't work.

**Comment by alialaa** [comment]
yes it worked, my mistake
